title: Amazonian Fish ML Classifier
description: Links to application, code, models, and data for "Application of a Deep Learning Image Classifier for Identification of Amazonian Fishes."
theme: jekyll-theme-cayman
github:
  is_project_page: false
